### ISSUE TITLE
Bug: Login with 2FA enabled not possible

### ISSUE THREAD

**Issue by mtettke123** [go-vikunja/app#11]
When I try to login to my account (secured by 2FA), I get:
![1659700727431](https://user-images.githubusercontent.com/82048170/183073547-eccb9a0a-8aad-4cf7-9df5-17c935813d7e.jpg)

... works on accounts with 2 FA not enabled. Using "login via web" is no solution, as this works only until the docker containers are restarted.

**Comment by kolaente** [comment]
How does it only work until the docker containers are restarted?

**Comment by mtettke123** [comment]
> How does it only work until the docker containers are restarted?

The app doesnt't work until I log out and in again when the docker containers (probably only the API one) are restarted. Have the same "problem" with the frontend: When the API is restarted, I need to log out of the frontend and in again. Thought at least for the frontend this is the normal behaviour?

**Comment by kolaente** [comment]
> Thought at least for the frontend this is the normal behaviour?

It's not. It sounds like the token invalidates because you didn't configure a jwt token. 

There's been a similar case in the forum: https://community.vikunja.io/t/user-sessions-are-lost-after-restart/726

Can you check if that's the problem you have? If not, please open a new issue in the api repo.

**Comment by Benimautner** [comment]
This is fixed in the newest release. It had something to do with dynamic error handling. Please report back whether it works and close the issue if it works.

**Comment by mtettke123** [comment]
JWT_SERVICE_TOKEN was not set, indeed. One Problem solved :-)

The other problem is solved with the newest release, too. Can now log in. Thank you!
