### ISSUE TITLE
"login with frontend" broken since the last release.

### ISSUE THREAD

**Issue by dorianim** [go-vikunja/app#12]
Unfortunately, it seems like the "login with fronten" function is broken since the last release.
When I click login with frontend, I just get a black screen, and the app crashes.

@Benimautner Feel free to use my Instance for testing, your credentials should still work :)

_Originally posted by @dorianim in https://github.com/go-vikunja/app/issues/3#issuecomment-1208603656_

**Comment by Benimautner** [comment]
Weird. It works on my phone as well as the emulator. Have you tried going into the settings and clearing the app's data? If that doesn't help either, please share some information about your device such as the make, model and android version.

**Comment by dorianim** [comment]
Oh, ok. I removed the app conpletely and installed it again. After that, it seemed to work and I could login using the browser. After clicking the login button a second time, it still gave a black screen. After restarting the app, though, I was logged in and everythung seems to work fine :)
