### ISSUE TITLE
task list keeps loading after adding additional lists

### ISSUE THREAD

**Issue by smignon612** [go-vikunja/app#21]
i'm using the 0.0.21 build.
when i installed the app the first list (that i share with my partner) appeared without any problems on the app of my phone and partners, same for the task.
a friend of my joined my server to, created a shared list with me and now i cant see any of the tasks list anymore (its stuck on the loading symbol). Same for my partner (who's only sharing a list with me).
My friend does not use the app

**Comment by Benimautner** [comment]
This is the same error that also happens when you have favourites, because the namespace owner of the shared namespace and the favourite namespace is null. Version 0.0.22-alpha should fix this.
Please close this issue if it has been fixed!

**Comment by smignon612** [comment]
it is working now thx
