### ISSUE TITLE
Feature Request: Easy import from Todoist

### ISSUE THREAD

**Issue by Tobi0812** [go-vikunja/app#23]
I am currently using Todoist but I want to switch and found Vikunja and I love it so far.
I would just love if I would have a possibility to import my tasks from Todoist with ease. I have over 100 tasks so to write down everything would not be the best idea.

**Comment by Benimautner** [comment]
This can be done through the import feature in the desktop app or web frontend. Are you selfhosting or are you using vikunja cloud?
If you are self hosting, you can check out this post to see how to configure the migrator: [link](https://community.vikunja.io/t/importing-tasks-from-todoist/322/5)
Or check out the part you need to modify in the config example: [link](https://kolaente.dev/vikunja/api/src/branch/main/config.yml.sample#L196-L201)
The flutter app (the repo you opened this issue on) will probably not support this in the near future.

**Comment by Tobi0812** [comment]
> This can be done through the import feature in the desktop app or web frontend. Are you selfhosting or are you using vikunja cloud? If you are self hosting, you can check out this post to see how to configure the migrator: [link](https://community.vikunja.io/t/importing-tasks-from-todoist/322/5) Or check out the part you need to modify in the config example: [link](https://kolaente.dev/vikunja/api/src/branch/main/config.yml.sample#L196-L201) The flutter app (the repo you opened this issue on) will probably not support this in the near future.

Got it, I didn't see it so I thought that Vikunja only supports migration from Vikunja Export and TickTick.
I am using the self-hosted version within a Docker container.
Thank you for your quick response, I'll close it since you showed me how to import my data :) Have a nice day and happy neww year!
