### ISSUE TITLE
Error message "Type Null is not a subtype of Type Map" when logging in with invalid credentials

### ISSUE THREAD

**Issue by kolaente** [go-vikunja/app#24]
Using the last release, logging with invalid credentials results in this error message:

![Screenshot_20230107-093900_Vikunja.png](https://user-images.githubusercontent.com/13721712/211141926-f2690fea-cebc-4b5f-b8cb-f27d70fb0d16.png)

There still is a correct error message in the toast at the bottom so the popup seems kind of redundant.

**Comment by Benimautner** [comment]
I removed the popup and made sure that the app does not make a second request if the first one fails. The error on a failed login should always be "wrong username or password" and never "missing or malformed jwt".
