### ISSUE TITLE
Use the new logo as app icon

### ISSUE THREAD

**Issue by kolaente** [go-vikunja/app#25]
The app seems to still use the old logo as an app icon:

![IMG_20230107_094332.jpg](https://user-images.githubusercontent.com/13721712/211142010-91dbe5da-b0c9-4d75-8ffb-b34d8951633e.jpg)

In the app the new logo is already used (for example on the login screen).

**Comment by Benimautner** [comment]
Changed in the newest release along with the notification logo which was offcentered before.
