### ISSUE TITLE
Invalid totp passcode

### ISSUE THREAD

**Issue by 0xCCD** [go-vikunja/app#31]
Today I've upgrade my docker container and the Android app to latest versions. 
Unfortunately the app stopped to ask me for my 2FA Token.

On the server log i see this error: 

```
api_1       | 2023-05-09T23:52:07.096393391Z: WEB 	▶ X.X.X.X  GET 200 /api/v1/info 139.641µs - Dart/2.17 (dart:io)
api_1       | 2023-05-09T23:52:07.362107267Z: ERROR	▶ v1/Login 6b1 Invalid totp passcode
api_1       | 2023-05-09T23:52:07.362142707Z: WEB 	▶ X.X.X.X POST 412 /api/v1/login 131.460525ms - Dart/2.17 (dart:io)
```

In the app I see "Error on request: Invalid totp passcode"

The problem is, the app never asks me for the code, only for Username and Password, Remember me

Is this a known issue or what could cause the problem ? 

FYI It started with v0.0.23-alpha and is still a problem in v0.0.25-alpha

Many thanks in advance

**Comment by kolaente** [comment]
Did this work before?

**Comment by 0xCCD** [comment]
It still work with v0.0.22-alpha for example
For all subsequent versions it does not work anymore

**Comment by Benimautner** [comment]
see [here](https://kolaente.dev/vikunja/api/issues/1518), it will be fixed in the next release.

**Comment by Benimautner** [comment]
This is fixed in the new release, let me know if it works for you @0xCCD.

**Comment by 0xCCD** [comment]
works great, ty
