### ISSUE TITLE
Front page only shows items with dates

### ISSUE THREAD

**Issue by slycat34** [go-vikunja/app#33]
Web version defaults to "overview" tab that shows a list of current tasks, whether they have dates or not. App version is only showing items that have a due date on them. I have to navigate to the individual namespaces to view a full list of tasks.

Is this by design? Could there be an option to view all current tasks as the "overview" page?

**Comment by Benimautner** [comment]
This is a good idea which has been on my roadmap for a while, I just haven't gotten around to it. Will come soon though!

**Comment by Benimautner** [comment]
You can now change this directly on the main page with the newest release. Just make sure to update your API to 0.21.0, as that's a breaking upgrade.
