### ISSUE TITLE
No visual indicator for priority

### ISSUE THREAD

**Issue by guidopetri** [go-vikunja/app#37]
It seems like setting a priority in a task doesn't have any visual indicator of the priority in the task list in the `Home` tab.

More broadly - is there a roadmap for what are the next features to be implemented, or just a general list of features to be implemented before a 1.0 release?

**Comment by Benimautner** [comment]
We do, this is the app roadmap: https://my.vikunja.cloud/share/BTZXIiomjxyQEdtsLmPkAKeRGkUCWUttgYbEyNIc/auth?view=kanban

**Comment by guidopetri** [comment]
Yep it works! Thanks!
