### ISSUE TITLE
Android native app notifications

### ISSUE THREAD

**Issue by Belgadon** [go-vikunja/app#42]
Hi,

If I get it right, the only (easy) wait to get notifications is via email.
Are there plans to use Android notifications via this App?

Thanks.

**Comment by kolaente** [comment]
App notifications should work, the app has to see the task though. Did you try setting a reminder in the app and then saw a notification?

**Comment by Belgadon** [comment]
I didn't have had enough patience.  I've always set the alarm to the next minute, but that didn't work.  With a little more time in advance it worked.

**Comment by s1lverkin** [comment]
Hmm, it doesn't work for me, when I am trying to configure a reminder, the setting just reverts to blank and no notifications are coming after that. Tested with some alarms in the next minute, 5 minutes, 30 minutes, hour, two hours, still nothing. The test notification in the settings menu works properly, but the notification on task is not working :(.

Pixel 8 Pro
