### ISSUE TITLE
Viewing all tasks on the home page shows them in a random order

### ISSUE THREAD

**Issue by kolaente** [go-vikunja/app#43]
If you deselect the option to show only tasks with a due date, it shows all tasks in a somewhat random order.

The frontend uses this to fetch tasks on its home page:

`/api/v1/tasks/all?sort_by[]=due_date&sort_by[]=id&order_by[]=asc&order_by[]=desc&filter_by[]=done&filter_value[]=false&filter_comparator[]=equals&filter_concat=and&filter_include_nulls=false&page=1`

This filter shows tasks with a due date first, sorted by their due date, and then sorts tasks based on their ID. This means recently created tasks will show up first. IMHO, the app should do something similar.

**Comment by Benimautner** [comment]
Ah yes, I finally found out why this happens. Will be fixed in the next release
