### ISSUE TITLE
Unhandled 401 Error "Bricks" App

### ISSUE THREAD

**Issue by JonahKr** [go-vikunja/app#45]
When changing your password via the webinterface the app tries to authenticate with the older credentials indefenitly. 
There is no way to escape this loop other than reinstalling the app. Ideally one would be prompted with the login screen again.
![markup_285 (2).png](https://github.com/go-vikunja/app/assets/38377070/014f0c83-0b6a-401e-a3a9-a538a75f0975)

**Comment by princelai** [comment]
Yes, the JWT key is set by default to 259200 (three days). The error is caused by the absence of an automatically issued JWT key if you don't log in for three days. You can try setting this value to 2592000, while also ensuring a login every month.

**Comment by kolaente** [comment]
> You can try setting this value to 2592000, while also ensuring a login every month.

Another option would be to use the frontend to login and then check the "remember me" checkbox.

**Comment by Benimautner** [comment]
You should be able to close messages like this by pressing the back button once. Then go to settings, click log out, and log in again. But yes, you're right, this shouldn't happen.

**Comment by Benimautner** [comment]
Closed due to inactivity. Open a new issue if you still need help.

**Comment by JonahKr** [comment]
The issue still persists. I don't think it is necessarily high priority but still.

**Comment by Benimautner** [comment]
I remember having the same issue some time ago. My problem was that I did not have a JWTSecret set, and so every time vikunja restarted it was rotated and I was logged out. Does this happen in the web interface as well?
What fixed it was adding this to my config.yml:

```
service:
  JWTSecret: <SECRET>
```

see [https://vikunja.io/docs/config-options/#jwtsecret](https://vikunja.io/docs/config-options/#jwtsecret)

**Comment by Benimautner** [comment]
After consulting with @kolaente I've expanded the app token refresh in the upcoming release to the level of the frontend. Every time you start the app and automatically every 12 hours the token should be refreshed, so it should never expire. I haven't extensively tried it myself but the refreshing on app launch definitely works, so please do let me know whether you still experience this with 0.1.4-beta.

**Comment by JonahKr** [comment]
The logout behaviour has definitely improved! Thanks a lot!

Still I think it would make sense to redirect the user to the login screen when the token is invalid for whatever reason. Then the user will be able to just login without having to navigate to the settings with the constant popup.

**Comment by Benimautner** [comment]
The app now logs you out if the token is expired.
