### ISSUE TITLE
Description shows HTML tags

### ISSUE THREAD

**Issue by wwwescape** [go-vikunja/app#50]
![Screenshot_2024-01-05-23-40-16-77_98965c6a1d1dd84fe3dc9a5899bc6fc7.jpg](https://github.com/go-vikunja/app/assets/651507/9cf02a5b-f7d1-4c7c-a7aa-44d42e47dbdd)

![Screenshot_2024-01-05-23-40-22-83_98965c6a1d1dd84fe3dc9a5899bc6fc7.jpg](https://github.com/go-vikunja/app/assets/651507/5370a87c-7c47-42c3-a7c0-33cbcce951d5)

**Comment by Benimautner** [comment]
The first one, in the task list, will be fixed in the upcoming release. The one on the task edit page, however, isn't as easy, and since it's only a textfield I have to think about how to change it to properly display the html.
