### ISSUE TITLE
Android native app notifications

### ISSUE THREAD

**Issue by s1lverkin** [go-vikunja/app#56]
Notificatios doesn't work for me, when I am trying to configure a reminder, the setting just reverts to blank and no notifications are coming after that. Tested with some alarms in the next minute, 5 minutes, 30 minutes, hour, two hours, still nothing. The test notification in the settings menu works properly, but the notification on task is not working :(.

Pixel 8 Pro

Duplicate of #42

**Comment by petebdeblois** [comment]
Having the same issue. Same phone.
No notifications at all

**Comment by Benimautner** [comment]
@s1lverkin @petebdeblois could you please share which android version you are using? I cannot reproduce this, even in a Pixel 8 Pro emulator.

**Comment by petebdeblois** [comment]
Sorry, my bad, I am on Pixel 7 Pro.
I installed the latest release 0.1.4-beta. Still same issue as on 3-beta. The "Send Test Notification" works.

Not getting the remainders notifications....
The App has permissions for Notifications

**Comment by Benimautner** [comment]
No worries at all, but that is still your phone, not your Android version. Could you please follow the below steps and post a screenshot of that page in the settings:

- Open your phone's Settings app.
- Near the bottom, tap About phone and then Android version.
- Find your "Android version," "Android security update," and "Build number".
- Screenshot and post here.

Thank you!

**Comment by petebdeblois** [comment]
![Screenshot_20240212-102525.png](https://github.com/go-vikunja/app/assets/20261852/debea75f-b787-4733-923a-c04f05824891)

There you go

**Comment by Benimautner** [comment]
Amazing, thanks! I will look into it and let you know. Android 14 is very new so I haven't tested it with the app yet. After a quick google search, this might be related: https://github.com/MaikuB/flutter_local_notifications/issues/2185. 
I will update you with any news!

**Comment by Benimautner** [comment]
Hey, could you try this:
https://we.tl/t-mM6qyUMJY8

if it doesn't work, please try a complete reinstall.

**Comment by petebdeblois** [comment]
Du did a fresh install but it doesn't open. It just keeps spinning.  ![Screenshot_20240212-184149.png](https://github.com/go-vikunja/app/assets/20261852/3a38659c-05fe-4d88-91a0-38c393d3e8a3)

Is there a way that I could give you some logs? That might help

**Comment by Benimautner** [comment]
That's very weird, I'm not sure what could be causing it. So you completely uninstalled and then reinstalled the app? Can you try to delete the app's data in the settings, then check if it starts?

As for logs, unfortunately it's not quite as easy. You can download logcat (https://play.google.com/store/apps/details?id=com.dp.logcatapp) and check for logs related to vikunja, but I find them misleading more often than not.

**Comment by petebdeblois** [comment]
I reinstall the last apk you sent and went to delete the cache... i really thought deleting the aopp first would have taken care of it.
Reopened the app and was able to enter my creds. 
Notif worked!

Thx a lot i can now use it!

**Comment by Benimautner** [comment]
Yeah, sometimes android is weird..
Very happy to hear that! I'll push out a release with these changes later today, then. Thanks for helping debug this!
