### ISSUE TITLE
Share with a default list

### ISSUE THREAD

**Issue by aleprovencio** [go-vikunja/app#63]
Hi ! First, thanks for your efforts on this app!

I'd like to propose a feature that I use a lot with other tasks managers, which for many years it was `OpenTasks` syncing with `Nextcloud`.

That is the ability to share items via an application's share menu, i.e.: You are browsing a website that you would like remember, so you open the 3-dot menu and click share, from there you choose can choose `vikunja` app.

The website will then appear on my inbox so then I can take an action the next time I deal with it.

**Comment by Benimautner** [comment]
This will be implemented in the 0.1.6-beta release, which will be released as soon as Vikunja 0.24 is released, since there are a bunch of breaking changes on the server side!

**Comment by Benimautner** [comment]
Done!
