### ISSUE TITLE
Automatic theme mode not applying

### ISSUE THREAD

**Issue by LageTs** [go-vikunja/app#64]
Hello,

I've identified an issue with the theme selection in the app. When set to "system" mode on Android 14 with LineageOS (OnePlus 5T), the app remains in the light mode even though the system is in dark mode.

It's interesting to note that the manual dark mode setting works as expected, but the automatic synchronization with the system mode seems to be malfunctioning.

Thank you!

**Comment by Benimautner** [comment]
Thanks for letting me know, I was able to reproduce this and will fix it in the next release.

**Comment by Benimautner** [comment]
Works now: https://github.com/go-vikunja/app/releases/tag/0.1.6-beta
Unfortunately, you have to restart the app when you change the theme. Funnily enough, it changes automatically when changing from dark->light for me, but not light->dark.
