### ISSUE TITLE
App opens but shows just a never ending circle

### ISSUE THREAD

**Issue by ruhlandm1** [go-vikunja/app#65]
Hello everybody - just installed the 0.1.5 version on my Pixel 5 Android 14 but I do not get anything else then a running circle. Any idea about that? 

Just tried the version 0.1.4 - that one works perfectly fine. Cleaning cache didn´t help.

**Comment by Benimautner** [comment]
Please try to clear data& cache of the app or try a reinstall. Let me know if you need help with either step.

**Comment by ruhlandm1** [comment]
Ok sorry for opening up an Issue - a simple reinstall did the job. Thank you for the amazing fast answer.

**Comment by ruhlandm1** [comment]
Reinstall - that did the job for me
