### ISSUE TITLE
Can't see all of the task details when description si to long 

### ISSUE THREAD

**Issue by RemusDumitrascu** [go-vikunja/app#77]
When the description of the task is too long the details are trimed and you can't scroll
![Screenshot_20240529-193646](https://github.com/go-vikunja/app/assets/18212454/004492be-fe0f-4cfd-bcd7-33edcbc0b54e)
I'm running the app version 0.1.5-beta on Android 14

**Comment by Benimautner** [comment]
Fixed in new version: https://github.com/go-vikunja/app/releases/tag/0.1.6-beta
