### ISSUE TITLE
Descriptions edited on the web ui show as plain html in the app edit mode 

### ISSUE THREAD

**Issue by RemusDumitrascu** [go-vikunja/app#78]
![Screenshot_20240529-193657](https://github.com/go-vikunja/app/assets/18212454/7654f257-c9fa-4f50-86fa-a5324a7b1ef5)
I'm using the app version 0.1.5-beta on Android 14

**Comment by Benimautner** [comment]
Yes that's unfortunately currently a limitation, thank's for bringing it up. If you want to view it, you can click on the task, not the edit symbol, to see it rendered. I'm not sure yet how I'll implement the edit feature.

**Comment by Benimautner** [comment]
The new app version now has an html editor: https://github.com/go-vikunja/app/releases/tag/0.1.6-beta
I'd love to get some feedback on it!

**Comment by Benimautner** [comment]
Closing this as fixed
