### ISSUE TITLE
Error: type 'Response' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by Krusty27** [go-vikunja/app#8]
This error happens when trying to add a new (non existent) lable inside a task.

![image](https://user-images.githubusercontent.com/28927643/168587318-c0263edf-7bd7-40ce-8627-4cadb7a766bd.png)

**Comment by Benimautner** [comment]
Sorry for the late reply, I was AFK for the last week.
This is an artefact from old times and is fixed in the new release.
The typeahead form still has bugs which I will fix another time, but at least it works now.
