### ISSUE TITLE
Non-latin characters in Projects

### ISSUE THREAD

**Issue by roburb** [go-vikunja/app#82]
Hi all,
thank you for great app.

I have updated the server to v0.24.0 an android app to 0.1.5-beta.

I have issue with non-latain characters in Project. The project name is not correctly shown.

Can someone help me please?
Thank you
Robert

**Comment by kolaente** [comment]
Do you have the same problem in the web frontend?

**Comment by Benimautner** [comment]
Can you reproduce this on https://try.vikunja.io?
If so, please share the non-latin characters that cause issues so I can reproduce this.

**Comment by roburb** [comment]
Hi,
I have tried to add the German chars on the web https://try.vikunja.io and with android app with same server address.
The chars are correctly shown on the web, not in app. Chars not correctly shown: ü ö ä á ě š and more
Thank you

**Comment by fyksen** [comment]
Same problem with Scandinavian letters like Æ, Ø and Å.

**Comment by belidzs** [comment]
App 0.1.6-beta still has this issue with server version v0.24.0-1-e16b1356ba

* Most text look like UTF-8 was displayed in ASCII
  * Text in reminder
  * Task title
  * Project title
* Frontend displays the same values correctly

**Comment by belidzs** [comment]
I believe this answer might be relevant here: https://stackoverflow.com/a/75646925/733440

https://github.com/go-vikunja/app/blob/4771de1a339f0bd26dfb1dbb50cde4332b8c10bf/lib/api/client.dart#L222-L226

**Comment by Benimautner** [comment]
Can you download the newest version here and try, please? It should fix that. @belidzs you were right, that was the issue, thanks!

https://github.com/go-vikunja/app/actions/runs/10240054475

**Comment by belidzs** [comment]
Nice, issue seems to be gone now

**Comment by wallon-ines** [comment]
> Can you download the newest version here and try, please? It should fix that. @belidzs you were right, that was the issue, thanks!
> 
> https://github.com/go-vikunja/app/actions/runs/10240054475

It's working for me too. Thanks
