### ISSUE TITLE
Error 404 when opening kanban

### ISSUE THREAD

**Issue by jonneolie** [go-vikunja/app#83]
When I go in the app to Projects --> My project --> Kanban. 
I get the following error:
Error code 404 received.
Details:
Error 404
Message: Not found
Url: https://***url****/api/v1/projects/2/buckets?page=1#

Also when I go directly to that URL it doesn't work, and I get a message: "missing, malformed, expired or otherwise invalid token provided" (but that might be because a webbrowser isn't an API call ofcourse).

I use the docker composed version, with NGINX infront of it.

**Comment by kolaente** [comment]
Which Vikunja Server version are zou u

**Comment by jonneolie** [comment]
I'm using Version: v0.24.0

**Comment by nagarrido** [comment]
Same happening here

**Comment by Benimautner** [comment]
Please try with the new release and close the issue if it's fixed: https://github.com/go-vikunja/app/releases/tag/0.1.6-beta

Unfortunately, tasks can't currently be moved between buckets.

**Comment by jonneolie** [comment]
Thank you, it's working!
