### ISSUE TITLE
Problem with Umlauts since 0.1.6-beta

### ISSUE THREAD

**Issue by escuco** [go-vikunja/app#85]
Hello!

First thank you for this cool piece of software, which I am using almost one year now.

After updating my Vikunja instance https://vikunja.klomp.de to 0.24.1 (from 0.23.??) and updating the Android app from 0.1.5-beta to 0.1.6-beta, all (german) umlauts are broken (in project names and also in task names).

![Screenshot_20240807-080617](https://github.com/user-attachments/assets/c317a523-2d7a-4dca-8d3c-a25efc9a626e)
The task should be "Bügel".

I don't know, if the api update or the app update caused the error. I think, it's the app, because in the web frontend and also in the desktop app the umlauts are still fine.

**Comment by Benimautner** [comment]
See: https://github.com/go-vikunja/app/issues/82
It's been solved and will be fixed in the new release

**Comment by escuco** [comment]
Sorry, didn't see that.

Thank you!
