### ISSUE TITLE
[BUG] Theme selection does not apply properly

### ISSUE THREAD

**Issue by DevGoran** [go-vikunja/app#86]
When switching too often between themes, the theme does not get applied visually until the application has been restarted.

For example: switching from light to dark works. When then in the same session the theme gets changed again to any other, then there is no visual change until the app has been reopened.

**Comment by Benimautner** [comment]
Yes I noticed exactly what you're describing - I have no idea why light->dark works but not the other way around. I've looked at it before but decided that there are more important features for now, since, as you mentioned, a restart of the app fixes it :)
