### ISSUE TITLE
Filtering for tasks with a due date only should use the api to filter

### ISSUE THREAD

**Issue by kolaente** [go-vikunja/app#94]
Here:

https://github.com/go-vikunja/app/blob/c62848b2acb866ec9536c3a556fc9369440b6d02/lib/pages/landing_page.dart#L278-L282

We're filtering tasks after loading them. This should be done using the api instead. A filter like `due_date > 0001-01-01` in combination with the `filter_include_nulls` parameter set to `false` should do the trick.

**Comment by Benimautner** [comment]
Absolutely! When I wrote that, the api (afaik) wasn't able to do that yet. I'll change it.

**Comment by Benimautner** [comment]
Fixed! FYI the filter needs a `due_date > 0001-01-01 00:00`. If it's just `0001-01-01`, it throws a server error 500. A more meaningful error would probably be great.
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/36c1d496-c1d0-4f3a-8c85-017ae7d3e1c6">
