### ISSUE TITLE
Icons on Project view not loading 

### ISSUE THREAD

**Issue by CrazyWolf13** [go-vikunja/app#96]
Hi 
I just tried the new latest, and seems like there is an issue with the icons:

When going into Projects->{Select a Project}-> see the non-working icons on the bottom.

![Screenshot_20241006_124127.jpg](https://github.com/user-attachments/assets/4d38118a-7a28-4f75-a7f0-2fa1b1b6ffc4)

Thanks, and btw the new design looks amazing!

**Comment by kolaente** [comment]
Which icons are not working?

Gantt and Table are not implemented.

**Comment by CrazyWolf13** [comment]
Oh I see!
